# Encoding fix
# --------------------------------------------------------------------
# APPLICATION
# --------------------------------------------------------------------
spring.application.name=ReaproAchat
server.address=0.0.0.0
server.port=8057

# --------------------------------------------------------------------
# DATASOURCE PRIMAIRE - POSTGRESQL (OBLIGATOIRE)
# --------------------------------------------------------------------
spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5432/ReaproAchat
spring.datasource.primary.username=postgres
spring.datasource.primary.password=postgres
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# HikariCP (facultatif mais fortement recommande)
spring.datasource.primary.hikari.maximum-pool-size=20


# --------------------------------------------------------------------
# DATASOURCE SECONDAIRE - SQL SERVER (Donnees externes - Lecture seule)
# --------------------------------------------------------------------
spring.datasource.sqlserver.jdbc-url=jdbc:sqlserver://192.168.1.6:1433;databaseName=Amiral_LS;encrypt=true;trustServerCertificate=true;integratedSecurity=false;
spring.datasource.sqlserver.username=sopiq
spring.datasource.sqlserver.password=*SoPiQ*123*2026
spring.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HikariCP optimise pour lecture
spring.datasource.sqlserver.hikari.maximum-pool-size=15
spring.datasource.sqlserver.hikari.minimum-idle=5
spring.datasource.sqlserver.hikari.connection-timeout=20000
spring.datasource.sqlserver.hikari.idle-timeout=600000
spring.datasource.sqlserver.hikari.read-only=true

# --------------------------------------------------------------------
# TECDOC - Configuration par defaut
# --------------------------------------------------------------------
# URL GW TECDOC
td.default.server-url=http://192.168.1.16:3030/tecdoc

# TECDOC API KEY
td.default.api-key=91Ph6tONctT6eXgpdf3I5EWF2ukvTLNiSq1y5T9012a0afa2f526ea00a05922d1
# TECDOC PROVIDER
td.default.provider=24879

# TECDOC COUNTRY
td.default.country=TN


# --------------------------------------------------------------------
# BUSINESS CENTRAL - Configuration par defaut
# --------------------------------------------------------------------
# URL de base du serveur BC (IP + Port)
bc.default.server-url=http://192.168.1.4:7148/

# Chemin API STANDARD (Microsoft)
bc.default.api-standard-path=BC160-PRODWS/api/beta

# Chemin API CUSTOM (votre extension SOPIQ)
bc.default.api-custom-path=BC160-PRODWS/api/sopiq/interne/v1.0

# Token d'authentification (Bearer Token)
bc.default.auth-token=R1JPVVBHXEFETUlOTkFWOlo1V2MzUHhZTDZKQm85dXh4cjBhSmNmNWdHRzVXNjlmOXRSeDlkOW9Cemc9

# Timeout en millisecondes
bc.default.timeout=30000
# --------------------------------------------------------------------
# JPA / HIBERNATE
# --------------------------------------------------------------------
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --------------------------------------------------------------------
# JWT CONFIG
# --------------------------------------------------------------------
app.secret-key=dbd77354091d911c319fbd9837c4f45b0a2ad33f3ae84ee04cf8ebe130d77b3a
jwt.refresh.secret.key=MaSuperCleRefreshQuiEstLongueEtSecrete123
app.expiration-time=900000
app.refresh-expiration-time=3600000

# --------------------------------------------------------------------
# MAIL (existant)
# --------------------------------------------------------------------
spring.mail.host=ssl0.ovh.net
spring.mail.port=587
spring.mail.username=notify@agence3s.tn
spring.mail.password=Not3S@2025*/
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# --------------------------------------------------------------------
# ENCODING
# --------------------------------------------------------------------
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# --------------------------------------------------------------------
# LOGGING
# --------------------------------------------------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.reapro.achat=DEBUG