spring.application.name=BackofficeAtelier
server.address=0.0.0.0
server.port=8055

# URL de connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/BackofficeAtelier
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#jwt variables
jwt.refresh.secret.key=MaSuperCleRefreshQuiEstLongueEtSecrete123
app.secret-key=dbd77354091d911c319fbd9837c4f45b0a2ad33f3ae84ee04cf8ebe130d77b3a


spring.mail.host=ssl0.ovh.net
spring.mail.port=587
spring.mail.username=notify@agence3s.tn
spring.mail.password=Not3S@2025*/
spring.mail.protocol=smtp
spring.mail.test-connection=true

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
# ===============================
# JWT CONFIG
# ===============================

# Access Token : 1HEURES
app.expiration-time=3600000

# Refresh Token : 8 1HEURES
app.refresh-expiration-time=28800000
